minimumReleaseAge: 0
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*

catalog:
  "@types/mdast": ^4.0.4
  "@types/node": ^26.2.0
  "@zinkawaii/eslint-config": ^0.5.3
  "@zinkawaii/scripts": ^0.0.5
  "@zinkawaii/tsconfig": ^0.1.0
  bumpp: ^12.2.1
  commonmark-spec: ^0.31.2
  entities: ^8.0.0
  eslint: ^10.8.1
  mdast-util-from-markdown: ^2.0.3
  mitata: ^1.0.34
  remark: ^15.0.1
  satteri: ^0.9.5
  tsdown: ^0.22.14
  vitest: ^4.1.10
