// Structural roles occupy the high bits so token emission never has to consult the profile.
export const enum BlockTokenRole {
  Raw,
  BlockOpen = 1 << 6,
  FrameOpen = 2 << 6,
  Close = 3 << 6,
  Leaf = 4 << 6,
  Group = 5 << 6,
}

export const enum BlockKind {
  None,
  InlineChunk,
  LinkDefinitionChunk,
  BlockComponentAttributes,

  BlockQuoteOpen = BlockTokenRole.BlockOpen,
  AtxHeadingOpen,
  SetextHeading1Open,
  SetextHeading2Open,
  ParagraphOpen,
  UnorderedListOpen,
  OrderedListOpen,
  LinkDefinitionOpen,
  FootnoteDefinitionOpen,
  TableOpen,
  BlockComponentOpen,
  BlockComponentSlotOpen,

  ListItemOpen = BlockTokenRole.FrameOpen,
  UncheckedTaskItemOpen,
  CheckedTaskItemOpen,
  TableRowOpen,
  TableCellStart,
  BlockComponentLabelOpen,

  BlockQuoteClose = BlockTokenRole.Close,
  HeadingClose,
  ParagraphClose,
  UnorderedListClose,
  OrderedListClose,
  ListItemClose,
  LinkDefinitionClose,
  FootnoteDefinitionClose,
  TableClose,
  TableRowClose,
  BlockComponentClose,
  BlockComponentLabelClose,
  BlockComponentSlotClose,

  ThematicBreak = BlockTokenRole.Leaf,
  FencedCodeBlock,
  IndentedCodeBlock,
  HtmlBlock,
  Frontmatter,
  MathBlock,
  BlockComponentYamlProps,

  TableAlignNone = BlockTokenRole.Group,
  TableAlignLeft,
  TableAlignRight,
  TableAlignCenter,
}

export const enum BlockRule {
  ThematicBreak,
  BlockQuote,
  AtxHeading,
  SetextHeading,
  Paragraph,
  ListItem,
  UnorderedList,
  OrderedList,
  FencedCode,
  IndentedCodeBlock,
  HtmlBlock,
  LinkDefinition,
  FootnoteDefinition,
  Frontmatter,
  MathBlock,
  Table,
  TableRow,
  TableCell,
  TableDelimiter,
  BlockComponent,
  BlockComponentLabel,
  BlockComponentYamlProps,
  BlockComponentSlot,
}
