export const enum Character {
  VirtualBlockIndent = -1,
  CharacterTabulation = 9,
  LineFeed,
  LineTabulation,
  FormFeed,
  CarriageReturn,
  Space = 32,
  ExclamationMark,
  QuotationMark,
  NumberSign,
  DollarSign,
  PercentSign,
  Ampersand,
  Apostrophe,
  LeftParenthesis,
  RightParenthesis,
  Asterisk,
  PlusSign,
  Comma,
  HyphenMinus,
  FullStop,
  Solidus,
  DigitZero,
  DigitOne,
  DigitTwo,
  DigitThree,
  DigitFour,
  DigitFive,
  DigitSix,
  DigitSeven,
  DigitEight,
  DigitNine,
  Colon,
  Semicolon,
  LessThanSign,
  EqualsSign,
  GreaterThanSign,
  QuestionMark,
  CommercialAt,
  LatinCapitalLetterA,
  LatinCapitalLetterX = 88,
  LatinCapitalLetterZ = 90,
  LeftSquareBracket,
  ReverseSolidus,
  RightSquareBracket,
  CircumflexAccent,
  LowLine,
  GraveAccent,
  LatinSmallLetterA,
  LatinSmallLetterX = 120,
  LatinSmallLetterZ = 122,
  LeftCurlyBracket,
  VerticalLine,
  RightCurlyBracket,
  Tilde,
  HighSurrogateStart = 0xD800,
  HighSurrogateEnd = 0xDBFF,
  LowSurrogateStart = 0xDC00,
  LowSurrogateEnd = 0xDFFF,
}
