name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v1

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test
